{"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/init(poseTheme:)"],"title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/cameraBuffer","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/cameraPosition","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/isEnabled","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/orientation","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/poseFeedback","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/positionFeedback","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/processedFrame","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/rawFrame","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/status","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/updateDeviceOrientation()"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/AVCaptureDataOutputSynchronizerDelegate-Implementations","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/ObservableObject-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(pl)AVCaptureDataOutputSynchronizerDelegate","doc:\/\/tech.prismlabs.prismsdk\/7Combine16ObservableObjectP","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSObject","doc:\/\/tech.prismlabs.prismsdk\/s7CVarArgP","doc:\/\/tech.prismlabs.prismsdk\/s8CopyableP","doc:\/\/tech.prismlabs.prismsdk\/s28CustomDebugStringConvertibleP","doc:\/\/tech.prismlabs.prismsdk\/s23CustomStringConvertibleP","doc:\/\/tech.prismlabs.prismsdk\/SQ","doc:\/\/tech.prismlabs.prismsdk\/SH"]}],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraSession"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Examples:","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"SwiftUI"}]},{"code":["@StateObject var session: CameraSession = CameraSession()"],"type":"codeListing","syntax":"swift"},{"style":"warning","type":"aside","name":"Warning","content":[{"inlineContent":[{"text":"This requires you to add the ","type":"text"},{"type":"codeVoice","code":"Privacy - Camera Usage Description"},{"type":"text","text":" "},{"type":"text","text":"key to your Info.plist file. Apple requires a description in detail of why"},{"type":"text","text":" "},{"type":"text","text":"you need access to the camera, and what you are doing with it."}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/camerasession"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/prismsdk\/camerasession"]}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK"]]},"sections":[],"kind":"symbol","metadata":{"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"title":"CameraSession","role":"symbol","modules":[{"name":"PrismSDK"}],"externalID":"c:@M@PrismSDK@objc(cs)CameraSession","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CameraSession","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"text":"poses from the user.","type":"text"}],"references":{"doc://tech.prismlabs.prismsdk/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s8CopyableP"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/visionDetection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"visionDetection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VisionDetectionState","preciseIdentifier":"s:8PrismSDK20VisionDetectionStateO"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection","type":"topic","title":"visionDetection","abstract":[{"type":"text","text":"Enable or Disable Vision Detection."},{"type":"text","text":" "},{"type":"text","text":"See "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection","isActive":true,"type":"reference"},{"type":"text","text":" for more information"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession\/visiondetection"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/positionFeedback":{"type":"topic","abstract":[{"type":"text","text":"An indicator of position acceptability"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/positionFeedback","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionFeedback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionFeedback","preciseIdentifier":"s:8PrismSDK17DetectionFeedbackO"},{"text":"?","kind":"text"}],"url":"\/documentation\/prismsdk\/camerasession\/positionfeedback","title":"positionFeedback","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/cameraBuffer":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraBuffer"},{"kind":"text","text":": "},{"text":"CameraBuffer","preciseIdentifier":"s:8PrismSDK12CameraBufferV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/cameraBuffer","type":"topic","title":"cameraBuffer","abstract":[{"text":"The full camera buffer data","type":"text"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession\/camerabuffer"},"doc://tech.prismlabs.prismsdk/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s28CustomDebugStringConvertibleP"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/ObservableObject-Implementations":{"kind":"article","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/ObservableObject-Implementations","type":"topic","title":"ObservableObject Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/prismsdk\/camerasession\/observableobject-implementations"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s7CVarArgP"},"doc://tech.prismlabs.prismsdk/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSObject"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/isEnabled":{"type":"topic","abstract":[{"text":"Enable or Disable the Camera Session","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/isEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/prismsdk\/camerasession\/isenabled","title":"isEnabled","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/AVCaptureDataOutputSynchronizerDelegate-Implementations":{"title":"AVCaptureDataOutputSynchronizerDelegate Implementations","kind":"article","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/AVCaptureDataOutputSynchronizerDelegate-Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/prismsdk\/camerasession\/avcapturedataoutputsynchronizerdelegate-implementations"},"doc://tech.prismlabs.prismsdk/objc(pl)AVCaptureDataOutputSynchronizerDelegate":{"title":"AVCaptureDataOutputSynchronizerDelegate","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)AVCaptureDataOutputSynchronizerDelegate"},"doc://tech.prismlabs.prismsdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s23CustomStringConvertibleP"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/processedFrame":{"abstract":[{"text":"The processed frame with any drawing on top","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/prismsdk\/camerasession\/processedframe","title":"processedFrame","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"processedFrame"},{"text":": ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/processedFrame"},"doc://tech.prismlabs.prismsdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(cs)NSObject"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/cameraPosition":{"url":"\/documentation\/prismsdk\/camerasession\/cameraposition","title":"cameraPosition","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/cameraPosition","abstract":[{"type":"text","text":"The Camera to use. We only support front facing right now, but the"},{"type":"text","text":" "},{"type":"text","text":"rear camera can also be used."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPosition","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/updateDeviceOrientation()":{"type":"topic","abstract":[],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/updateDeviceOrientation()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateDeviceOrientation","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/prismsdk\/camerasession\/updatedeviceorientation()","title":"updateDeviceOrientation()","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/poseFeedback":{"url":"\/documentation\/prismsdk\/camerasession\/posefeedback","title":"poseFeedback","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/poseFeedback","abstract":[{"text":"An indicator of pose acceptability","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"poseFeedback"},{"text":": ","kind":"text"},{"text":"DetectionFeedback","kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK17DetectionFeedbackO"},{"text":"?","kind":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/orientation":{"type":"topic","abstract":[{"text":"The Device orientation (landscape or portrait)","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/orientation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"}],"url":"\/documentation\/prismsdk\/camerasession\/orientation","title":"orientation","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/7Combine16ObservableObjectP":{"title":"Combine.ObservableObject","identifier":"doc:\/\/tech.prismlabs.prismsdk\/7Combine16ObservableObjectP","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/SQ","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/SH","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/status":{"type":"topic","abstract":[{"text":"The permission status for the camera","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraPermissionStatus","preciseIdentifier":"s:8PrismSDK22CameraPermissionStatusO","kind":"typeIdentifier"}],"url":"\/documentation\/prismsdk\/camerasession\/status","title":"status","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/rawFrame":{"title":"rawFrame","type":"topic","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/rawFrame","url":"\/documentation\/prismsdk\/camerasession\/rawframe","abstract":[{"text":"The raw frame from the camera without any post processing","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/init(poseTheme:)":{"type":"topic","abstract":[{"text":"A convience initializer to instantiate the camera and initialize the feed","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/init(poseTheme:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"poseTheme"},{"text":": ","kind":"text"},{"text":"PoseTheme","kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK9PoseThemeV"},{"text":")","kind":"text"}],"url":"\/documentation\/prismsdk\/camerasession\/init(posetheme:)","title":"init(poseTheme:)","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"CameraSession","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"CameraSession","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"CameraSession"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/AVCaptureDataOutputSynchronizerDelegate-Implementations"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(pl)AVCaptureDataOutputSynchronizerDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraSession","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title","value":"CameraSession"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments","value":[{"text":"CameraSession","kind":"identifier"}]},{"value":[{"text":"CameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","op":"replace"}]}]}