{"sections":[],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/init()"],"anchor":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/isUploading","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/progress","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/uploadedFile"]},{"title":"Instance Methods","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/setup()","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/upload(file:to:)"],"anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/ObservableObject-Implementations","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionDelegate-Implementations","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/7Combine16ObservableObjectP","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSURLSessionDelegate","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSObject","doc:\/\/tech.prismlabs.prismsdk\/s7CVarArgP","doc:\/\/tech.prismlabs.prismsdk\/s8CopyableP","doc:\/\/tech.prismlabs.prismsdk\/s28CustomDebugStringConvertibleP","doc:\/\/tech.prismlabs.prismsdk\/s23CustomStringConvertibleP","doc:\/\/tech.prismlabs.prismsdk\/SQ","doc:\/\/tech.prismlabs.prismsdk\/SH","doc:\/\/tech.prismlabs.prismsdk\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader"]},{"paths":["\/documentation\/prismsdk\/fileuploader"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK"]]},"metadata":{"modules":[{"name":"PrismSDK"}],"title":"FileUploader","navigatorTitle":[{"kind":"identifier","text":"FileUploader"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileUploader"}],"roleHeading":"Class","externalID":"c:@M@PrismSDK@objc(cs)FileUploader","role":"symbol","symbolKind":"class"},"abstract":[{"type":"text","text":"File Uploader handles uploading the Scan"}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/ObservableObject-Implementations":{"url":"\/documentation\/prismsdk\/fileuploader\/observableobject-implementations","kind":"article","title":"ObservableObject Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/ObservableObject-Implementations","type":"topic"},"doc://tech.prismlabs.prismsdk/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s8SendableP"},"doc://tech.prismlabs.prismsdk/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s8CopyableP"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/URLSessionDelegate-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiondelegate-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionDelegate-Implementations","title":"URLSessionDelegate Implementations"},"doc://tech.prismlabs.prismsdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/SH"},"doc://tech.prismlabs.prismsdk/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSObject"},"doc://tech.prismlabs.prismsdk/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s7CVarArgP"},"doc://tech.prismlabs.prismsdk/objc(pl)NSURLSessionDelegate":{"type":"unresolvable","title":"NSURLSessionDelegate","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSURLSessionDelegate"},"doc://tech.prismlabs.prismsdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s28CustomDebugStringConvertibleP"},"doc://tech.prismlabs.prismsdk/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/setup()":{"url":"\/documentation\/prismsdk\/fileuploader\/setup()","title":"setup()","abstract":[{"type":"text","text":"Setups the uploader for use"},{"type":"text","text":" "},{"text":"This will also resume any suspended tasks and continue running them as needed.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/setup()","role":"symbol","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/isUploading":{"role":"symbol","url":"\/documentation\/prismsdk\/fileuploader\/isuploading","kind":"symbol","type":"topic","abstract":[],"title":"isUploading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isUploading","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/isUploading"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(cs)NSObject","title":"NSObject"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/init()":{"url":"\/documentation\/prismsdk\/fileuploader\/init()","title":"init()","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/objc(pl)NSURLSessionTaskDelegate":{"type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSURLSessionTaskDelegate","title":"NSURLSessionTaskDelegate"},"doc://tech.prismlabs.prismsdk/7Combine16ObservableObjectP":{"type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/7Combine16ObservableObjectP","title":"Combine.ObservableObject"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/upload(file:to:)":{"role":"symbol","abstract":[{"text":"Upload a File to a Generated URL","type":"text"}],"type":"topic","title":"upload(file:to:)","url":"\/documentation\/prismsdk\/fileuploader\/upload(file:to:)","kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/upload(file:to:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"upload","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/URLSessionTaskDelegate-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiontaskdelegate-implementations","type":"topic","role":"collectionGroup","title":"URLSessionTaskDelegate Implementations","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"},"doc://tech.prismlabs.prismsdk/SQ":{"type":"unresolvable","identifier":"doc:\/\/tech.prismlabs.prismsdk\/SQ","title":"Swift.Equatable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/progress":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/progress","title":"progress","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/prismsdk\/fileuploader\/progress","type":"topic","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/uploadedFile":{"abstract":[],"url":"\/documentation\/prismsdk\/fileuploader\/uploadedfile","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/uploadedFile","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"uploadedFile","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"uploadedFile"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"FileUploader"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"FileUploader"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FileUploader"}],"op":"replace"},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/init()"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionDelegate-Implementations","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSURLSessionDelegate","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSURLSessionTaskDelegate"],"title":"Conforms To"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileUploader","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title","op":"replace","value":"FileUploader"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments","op":"replace","value":[{"kind":"identifier","text":"FileUploader"}]},{"value":[{"kind":"identifier","text":"FileUploader"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1init()\/title","value":"init","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1init()\/fragments","op":"replace"}]}]}