{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrismSessionViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"Examples:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"UIKit"}]},{"type":"codeListing","code":["let captureViewController = PrismSessionViewController(theme: .default, delegate: self)","self.present(captureViewController, animated: true)"],"syntax":"swift"},{"inlineContent":[{"type":"text","text":"The Delegate is optional, but is required to do anything meaningful with the capture."},{"text":" ","type":"text"},{"type":"text","text":"UIKit"}],"type":"paragraph"},{"syntax":"swift","code":["func prismSession(_ controller: PrismSessionViewController, didRecieveArchive archive: URL) {","   print(\"Recording File URL: \\(archive)\")","}","","func prismSession(willDismiss controller: PrismSessionViewController) {","   controller.dismiss(animated: true)","}"],"type":"codeListing"},{"name":"Warning","style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This requires you to add the "},{"code":"Privacy - Camera Usage Description","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"key to your Info.plist file. Apple requires a description in detail of why"},{"text":" ","type":"text"},{"type":"text","text":"you need access to the camera, and what you are doing with it."}]}]}]}],"metadata":{"modules":[{"name":"PrismSDK"}],"roleHeading":"Class","title":"PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PrismSessionViewController","kind":"identifier"}],"externalID":"c:@M@PrismSDK@objc(cs)PrismSessionViewController","role":"symbol","navigatorTitle":[{"text":"PrismSessionViewController","kind":"identifier"}],"symbolKind":"class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK"]]},"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSCoding","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSExtensionRequestHandling","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSObject","doc:\/\/tech.prismlabs.prismsdk\/s7CVarArgP","doc:\/\/tech.prismlabs.prismsdk\/s28CustomDebugStringConvertibleP","doc:\/\/tech.prismlabs.prismsdk\/s23CustomStringConvertibleP","doc:\/\/tech.prismlabs.prismsdk\/SQ","doc:\/\/tech.prismlabs.prismsdk\/SH","doc:\/\/tech.prismlabs.prismsdk\/s8SendableP","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIAppearanceContainer","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIContentContainer","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIFocusEnvironment","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIResponderStandardEditActions","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIStateRestoring","doc:\/\/tech.prismlabs.prismsdk\/5UIKit23UITraitChangeObservableP","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UITraitEnvironment","doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/prismsessionviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/prismsdk\/prismsessionviewcontroller"]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/init(theme:delegate:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/viewDidLoad()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"seeAlsoSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate"],"anchor":"Capture-UI","generated":true,"title":"Capture UI"}],"abstract":[{"type":"text","text":"PrismSessionViewController functions as the one-stop Capture View."},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"text":" ","type":"text"},{"text":"and posing of the person. This is to help simplify the entire process.","type":"text"}],"sections":[],"references":{"doc://tech.prismlabs.prismsdk/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/SQ":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/s7CVarArgP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView":{"kind":"symbol","title":"PrismSessionView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionView"}],"abstract":[{"text":"The entire Capture Session Flow","type":"text"}],"url":"\/documentation\/prismsdk\/prismsessionview","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrismSessionView"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","role":"symbol"},"doc://tech.prismlabs.prismsdk/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/s23CustomStringConvertibleP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/SH":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController/viewDidLoad()":{"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/viewDidLoad()","kind":"symbol","title":"viewDidLoad()","url":"\/documentation\/prismsdk\/prismsessionviewcontroller\/viewdidload()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}]},"doc://tech.prismlabs.prismsdk/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIFocusEnvironment"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController/init(theme:delegate:)":{"abstract":[{"type":"text","text":"Creates a "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","type":"reference","isActive":true},{"text":" to faciliate the recording of a body scan.","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/init(theme:delegate:)","kind":"symbol","title":"init(theme:delegate:)","url":"\/documentation\/prismsdk\/prismsessionviewcontroller\/init(theme:delegate:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8PrismSDK0A18ThemeConfigurationV","kind":"typeIdentifier","text":"PrismThemeConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrismSessionViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK0A29SessionViewControllerDelegateP"},{"text":"?)","kind":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/s8SendableP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)NSCoding":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)NSObject":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(cs)UIViewController":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/objc(pl)UIContentContainer":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"PrismSessionViewController","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"PrismSessionViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PrismSessionViewController","kind":"identifier"}]},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/viewDidLoad()"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"PrismSessionViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController~1viewDidLoad()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title","value":"PrismSessionViewController","op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments","value":[{"kind":"identifier","text":"PrismSessionViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PrismSessionViewController"}]}]}]}