{"abstract":[{"text":"The entire Capture Session Flow","type":"text"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/s8SendableP","doc:\/\/tech.prismlabs.prismsdk\/7SwiftUI4ViewP"],"kind":"relationships","type":"conformsTo"}],"metadata":{"navigatorTitle":[{"text":"PrismSessionView","kind":"identifier"}],"externalID":"s:8PrismSDK0A11SessionViewV","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionView"}],"role":"symbol","title":"PrismSessionView","symbolKind":"struct","modules":[{"name":"PrismSDK"}],"roleHeading":"Structure"},"sections":[],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/init(receivedArchive:onStatus:onDismiss:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/body"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/View-Implementations","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/View-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"seeAlsoSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate"],"title":"Capture UI","generated":true,"anchor":"Capture-UI"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/prismsessionview"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PrismSessionView","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This creates the entire capture complete, complete with leveling,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"positioning, posing, and recording."}]}]}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView/body":{"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/body","title":"body","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/prismsdk\/prismsessionview\/body","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"body"},{"text":": ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView/View-Implementations":{"url":"\/documentation\/prismsdk\/prismsessionview\/view-implementations","role":"collectionGroup","title":"View Implementations","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/View-Implementations","type":"topic","abstract":[],"kind":"article"},"doc://tech.prismlabs.prismsdk/s8SendableP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/7SwiftUI4ViewP":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/7SwiftUI4ViewP","title":"SwiftUICore.View","type":"unresolvable"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView":{"kind":"symbol","title":"PrismSessionView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionView"}],"abstract":[{"text":"The entire Capture Session Flow","type":"text"}],"url":"\/documentation\/prismsdk\/prismsessionview","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrismSessionView"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView/init(receivedArchive:onStatus:onDismiss:)":{"kind":"symbol","abstract":[{"text":"Instantiates a new ","type":"text"},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","isActive":true,"type":"reference"}],"type":"topic","title":"init(receivedArchive:onStatus:onDismiss:)","url":"\/documentation\/prismsdk\/prismsessionview\/init(receivedarchive:onstatus:ondismiss:)","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView\/init(receivedArchive:onStatus:onDismiss:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"receivedArchive"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onStatus","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:8PrismSDK19CaptureSessionStateO","text":"CaptureSessionState","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onDismiss"},{"kind":"text","text":": () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title","op":"replace","value":"PrismSessionViewController"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments","value":[{"text":"PrismSessionViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PrismSessionViewController"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}