{"abstract":[{"type":"text","text":"The delegate callbacks for the "},{"type":"reference","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true}],"topicSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(_:didChangeStatus:)","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(_:didRecieveArchive:)","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(willDismiss:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate"]}],"metadata":{"externalID":"s:8PrismSDK0A29SessionViewControllerDelegateP","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"roleHeading":"Protocol","role":"symbol","title":"PrismSessionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"modules":[{"name":"PrismSDK"}]},"seeAlsoSections":[{"title":"Capture UI","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController"],"generated":true,"anchor":"Capture-UI"}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK"]]},"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PrismSessionViewControllerDelegate","kind":"identifier"},{"text":" : AnyObject","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate/prismSession(_:didRecieveArchive:)":{"title":"prismSession(_:didRecieveArchive:)","abstract":[{"type":"text","text":"When a capture and an archive completes"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(_:didrecievearchive:)","required":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(_:didRecieveArchive:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"prismSession"},{"text":"(","kind":"text"},{"text":"PrismSessionViewController","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRecieveArchive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":")","kind":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate/prismSession(willDismiss:)":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(willdismiss:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"kind":"text","text":"("},{"text":"willDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrismSessionViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController"},{"kind":"text","text":")"}],"title":"prismSession(willDismiss:)","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(willDismiss:)","abstract":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true},{"type":"text","text":" that will dimiss"}],"required":true,"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate/prismSession(_:didChangeStatus:)":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(_:didChangeStatus:)","kind":"symbol","title":"prismSession(_:didChangeStatus:)","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(_:didchangestatus:)","abstract":[{"text":"When the capture state changes","type":"text"}],"role":"symbol","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PrismSessionViewController","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8PrismSDK19CaptureSessionStateO","kind":"typeIdentifier","text":"CaptureSessionState"},{"kind":"text","text":")"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView":{"kind":"symbol","title":"PrismSessionView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionView"}],"abstract":[{"text":"The entire Capture Session Flow","type":"text"}],"url":"\/documentation\/prismsdk\/prismsessionview","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrismSessionView"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title","value":"PrismSessionViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments","value":[{"text":"PrismSessionViewController","kind":"identifier"}]},{"value":[{"text":"PrismSessionViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle","op":"replace"}]}]}