{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"externalID":"s:8PrismSDK0A21SessionViewControllerC5theme8delegateAcA0A18ThemeConfigurationV_AA0acdE8Delegate_pSgtcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"text":"PrismThemeConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK0A18ThemeConfigurationV"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8PrismSDK0A29SessionViewControllerDelegateP","text":"PrismSessionViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"modules":[{"name":"PrismSDK"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(theme:delegate:)"},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController"]]},"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/init(theme:delegate:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/prismsessionviewcontroller\/init(theme:delegate:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"text":"PrismThemeConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismThemeConfiguration","preciseIdentifier":"s:8PrismSDK0A18ThemeConfigurationV"},{"kind":"text","text":" = .default, "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK0A29SessionViewControllerDelegateP","text":"PrismSessionViewControllerDelegate","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"theme","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The theme configuration to apply to the session (Refer to "},{"type":"reference","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismThemeConfiguration","isActive":true},{"text":" for options)","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional delegate to return capture information"}]}],"name":"delegate"}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"UIKit","type":"text"}]},{"type":"codeListing","code":["let captureViewController = PrismSessionViewController(theme: .default, delegate: self)"],"syntax":"swift"}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"Creates a ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController"},{"type":"text","text":" to faciliate the recording of a body scan."}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController/init(theme:delegate:)":{"abstract":[{"type":"text","text":"Creates a "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","type":"reference","isActive":true},{"text":" to faciliate the recording of a body scan.","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController\/init(theme:delegate:)","kind":"symbol","title":"init(theme:delegate:)","url":"\/documentation\/prismsdk\/prismsessionviewcontroller\/init(theme:delegate:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8PrismSDK0A18ThemeConfigurationV","kind":"typeIdentifier","text":"PrismThemeConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrismSessionViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK0A29SessionViewControllerDelegateP"},{"text":"?)","kind":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismThemeConfiguration":{"title":"PrismThemeConfiguration","abstract":[{"text":"Defines all of the available properties for theming the PrismSession","type":"text"}],"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismThemeConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/prismsdk\/prismthemeconfiguration","navigatorTitle":[{"text":"PrismThemeConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismThemeConfiguration"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title","value":"PrismSessionViewController","op":"replace"},{"value":[{"text":"PrismSessionViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments","op":"replace"},{"op":"replace","value":[{"text":"PrismSessionViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}