{"variants":[{"paths":["\/documentation\/prismsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/prismsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Capture-FLow","title":"Capture FLow","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismCaptureSession"]},{"anchor":"Capture-UI","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate"],"title":"Capture UI"},{"anchor":"Classes","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ApiClient","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSession","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/MotionDetector","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismRecording"],"generated":true,"title":"Classes"},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismStateManager"],"anchor":"Protocols","generated":true,"title":"Protocols"},{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Asset","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/AssetUrls","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyShapePrediction","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyShapePredictionAssetUrl","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyShapePredictionPayload","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Bodyfat","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraBuffer","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSessionConfiguration","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ExistingUser","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Height","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Measurements","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/NewScan","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/NewUser","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PageInfo","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Paginated","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PoseTheme","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrimaryActionButtonStyle","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismError","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismThemeConfiguration","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Scan","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ScanAsset","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ScanClient","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/SecondaryActionButtonStyle","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/SimplePrimaryActionButtonStyle","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/TermsOfService","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/UploadUrl","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/User","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/UserClient","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Version","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Weight"],"title":"Structures","anchor":"Structures","generated":true},{"anchor":"Type-Aliases","title":"Type Aliases","generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ApiClientBearerToken"]},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ApiClientError","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/AssetConfigId","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyfatMethod","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraPermissionStatus","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureError","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSessionState","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/DetectionFailure","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/DetectionFeedback","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/NetworkingError","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PoseProblem","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PoseResult","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PositioningProblem","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PositioningResult","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismState","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Sex","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Sort","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/VisionDetectionState"],"anchor":"Enumerations"},{"generated":true,"title":"Extended Modules","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Foundation","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/SwiftUICore"],"anchor":"Extended-Modules"}],"kind":"symbol","hierarchy":{"paths":[[]]},"sections":[],"abstract":[{"text":"Full Body Scanning","type":"text"}],"metadata":{"modules":[{"name":"PrismSDK"}],"title":"PrismSDK","externalID":"PrismSDK","symbolKind":"module","role":"collection","roleHeading":"Framework"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"PrismKit handles all of the low level functions and allows you to implement full body scanning.","type":"text"}]}]}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CaptureSession":{"url":"\/documentation\/prismsdk\/capturesession","abstract":[{"type":"text","text":"Capture Session"}],"navigatorTitle":[{"text":"CaptureSession","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureSession"}],"title":"CaptureSession","kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSession","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/SimplePrimaryActionButtonStyle":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SimplePrimaryActionButtonStyle"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/SimplePrimaryActionButtonStyle","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SimplePrimaryActionButtonStyle","kind":"identifier"}],"url":"\/documentation\/prismsdk\/simpleprimaryactionbuttonstyle","abstract":[{"type":"text","text":"Used as the Primary Action button for all CTA style buttons"}],"title":"SimplePrimaryActionButtonStyle"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PoseResult":{"url":"\/documentation\/prismsdk\/poseresult","title":"PoseResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PoseResult"}],"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PoseResult","abstract":[{"type":"text","text":"PoseResult returns the high level results"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PoseResult"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Foundation":{"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Foundation","role":"collection","title":"Foundation","url":"\/documentation\/prismsdk\/foundation","abstract":[],"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/VisionDetectionState":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisionDetectionState"}],"navigatorTitle":[{"text":"VisionDetectionState","kind":"identifier"}],"title":"VisionDetectionState","abstract":[{"type":"text","text":"Vision Detection State"}],"url":"\/documentation\/prismsdk\/visiondetectionstate","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/VisionDetectionState","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Sort":{"type":"topic","abstract":[{"text":"Sorting values","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Sort"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Sort"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Sort","title":"Sort","kind":"symbol","url":"\/documentation\/prismsdk\/sort","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PoseTheme":{"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PoseTheme","url":"\/documentation\/prismsdk\/posetheme","title":"PoseTheme","abstract":[{"text":"Defines all of the available properties for theming the Pose Drawing","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"PoseTheme","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PoseTheme"}],"role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Measurements":{"title":"Measurements","navigatorTitle":[{"text":"Measurements","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Measurements"}],"role":"symbol","type":"topic","url":"\/documentation\/prismsdk\/measurements","kind":"symbol","abstract":[{"type":"text","text":"The Measurements results from a scan"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Measurements"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/DetectionFailure":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/DetectionFailure","kind":"symbol","url":"\/documentation\/prismsdk\/detectionfailure","navigatorTitle":[{"text":"DetectionFailure","kind":"identifier"}],"type":"topic","title":"DetectionFailure","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionFailure"}],"role":"symbol","abstract":[{"text":"Detection Failures for positioning and posing","type":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/NetworkingError":{"abstract":[{"text":"Networking error’s","type":"text"}],"type":"topic","title":"NetworkingError","url":"\/documentation\/prismsdk\/networkingerror","kind":"symbol","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/NetworkingError","navigatorTitle":[{"kind":"identifier","text":"NetworkingError"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkingError"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Version":{"title":"Version","kind":"symbol","role":"symbol","url":"\/documentation\/prismsdk\/version","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Version","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Version","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Version","kind":"identifier"}],"abstract":[]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/TermsOfService":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/TermsOfService","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TermsOfService"}],"title":"TermsOfService","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TermsOfService"}],"abstract":[],"url":"\/documentation\/prismsdk\/termsofservice","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismStateManager":{"role":"symbol","url":"\/documentation\/prismsdk\/prismstatemanager","kind":"symbol","type":"topic","abstract":[{"text":"Prism State Manager","type":"text"}],"title":"PrismStateManager","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismStateManager"}],"navigatorTitle":[{"kind":"identifier","text":"PrismStateManager"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismStateManager"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/BodyShapePredictionAssetUrl":{"url":"\/documentation\/prismsdk\/bodyshapepredictionasseturl","title":"BodyShapePredictionAssetUrl","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyShapePredictionAssetUrl","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"BodyShapePredictionAssetUrl","kind":"identifier"}],"abstract":[{"type":"text","text":"Asset URL that contains all files generated by the body shape prediction"}],"navigatorTitle":[{"text":"BodyShapePredictionAssetUrl","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/User":{"url":"\/documentation\/prismsdk\/user","navigatorTitle":[{"kind":"identifier","text":"User"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/User","kind":"symbol","abstract":[{"text":"A User Model returned from the Prism API to describe the active person.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"User","kind":"identifier"}],"title":"User"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/ScanClient":{"type":"topic","abstract":[{"type":"text","text":"ScanClient contains all of the API calls for creating,"},{"type":"text","text":" "},{"text":"fetching, and uploading scan information. This includes","type":"text"},{"type":"text","text":" "},{"type":"text","text":"generting the Upload URL."}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScanClient"}],"url":"\/documentation\/prismsdk\/scanclient","title":"ScanClient","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ScanClient","navigatorTitle":[{"text":"ScanClient","kind":"identifier"}],"kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PoseProblem":{"url":"\/documentation\/prismsdk\/poseproblem","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PoseProblem","abstract":[{"type":"text","text":"All available Pose Problems"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PoseProblem"}],"title":"PoseProblem","navigatorTitle":[{"kind":"identifier","text":"PoseProblem"}],"role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CaptureSessionState":{"abstract":[{"text":"The states of the ","type":"text"},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSession","isActive":true,"type":"reference"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureSessionState"}],"kind":"symbol","type":"topic","url":"\/documentation\/prismsdk\/capturesessionstate","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSessionState","title":"CaptureSessionState","navigatorTitle":[{"text":"CaptureSessionState","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/DetectionFeedback":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DetectionFeedback","kind":"identifier"}],"url":"\/documentation\/prismsdk\/detectionfeedback","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/DetectionFeedback","title":"DetectionFeedback","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DetectionFeedback","kind":"identifier"}],"abstract":[{"type":"text","text":"DetectionFeedback returns the high level results"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Height":{"type":"topic","abstract":[{"text":"Height information for the scan","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Height","navigatorTitle":[{"kind":"identifier","text":"Height"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Height","kind":"identifier"}],"url":"\/documentation\/prismsdk\/height","title":"Height","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/AssetConfigId":{"title":"AssetConfigId","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/AssetConfigId","abstract":[{"text":"AssetConfigId contains the supported scan asset bundles","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AssetConfigId"}],"role":"symbol","url":"\/documentation\/prismsdk\/assetconfigid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AssetConfigId","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PageInfo":{"abstract":[{"type":"text","text":"Returns all metadata about the page the data is returned from"}],"role":"symbol","navigatorTitle":[{"text":"PageInfo","kind":"identifier"}],"title":"PageInfo","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PageInfo","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PageInfo","kind":"identifier"}],"url":"\/documentation\/prismsdk\/pageinfo"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Bodyfat":{"title":"Bodyfat","abstract":[{"text":"BodyFat returns the scan details around Body Fat and Lean Mass","type":"text"}],"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Bodyfat","role":"symbol","kind":"symbol","url":"\/documentation\/prismsdk\/bodyfat","navigatorTitle":[{"kind":"identifier","text":"Bodyfat"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Bodyfat","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismState":{"abstract":[{"type":"text","text":"The state of the State Manager"}],"role":"symbol","navigatorTitle":[{"text":"PrismState","kind":"identifier"}],"title":"PrismState","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismState","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PrismState","kind":"identifier"}],"url":"\/documentation\/prismsdk\/prismstate"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismRecording":{"abstract":[],"title":"PrismRecording","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PrismRecording","kind":"identifier"}],"url":"\/documentation\/prismsdk\/prismrecording","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismRecording"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismRecording"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismError":{"kind":"symbol","navigatorTitle":[{"text":"PrismError","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismError","title":"PrismError","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The PrismError contains the decoded messages from the Prism API"}],"url":"\/documentation\/prismsdk\/prismerror","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismError"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Weight":{"abstract":[{"text":"Weight information for the scan","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"Weight","navigatorTitle":[{"kind":"identifier","text":"Weight"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Weight","url":"\/documentation\/prismsdk\/weight","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Weight"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrimaryActionButtonStyle":{"abstract":[{"type":"text","text":"Used as the Primary Action button for all CTA style buttons"}],"url":"\/documentation\/prismsdk\/primaryactionbuttonstyle","kind":"symbol","title":"PrimaryActionButtonStyle","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrimaryActionButtonStyle","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"PrimaryActionButtonStyle","kind":"identifier"}],"navigatorTitle":[{"text":"PrimaryActionButtonStyle","kind":"identifier"}],"role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/UploadUrl":{"role":"symbol","kind":"symbol","type":"topic","title":"UploadUrl","url":"\/documentation\/prismsdk\/uploadurl","navigatorTitle":[{"kind":"identifier","text":"UploadUrl"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UploadUrl"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/UploadUrl","abstract":[{"text":"Upload URL object","type":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/BodyfatMethod":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BodyfatMethod","kind":"identifier"}],"title":"BodyfatMethod","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyfatMethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BodyfatMethod"}],"url":"\/documentation\/prismsdk\/bodyfatmethod","type":"topic","abstract":[]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/ScanAsset":{"kind":"symbol","url":"\/documentation\/prismsdk\/scanasset","navigatorTitle":[{"text":"ScanAsset","kind":"identifier"}],"title":"ScanAsset","type":"topic","role":"symbol","abstract":[{"text":"The scan asset information","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScanAsset"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ScanAsset"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/ApiClientError":{"abstract":[{"text":"Api Client Error","type":"text"}],"url":"\/documentation\/prismsdk\/apiclienterror","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApiClientError"}],"navigatorTitle":[{"text":"ApiClientError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ApiClientError","title":"ApiClientError"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Scan":{"navigatorTitle":[{"kind":"identifier","text":"Scan"}],"abstract":[{"text":"Returned Scan Object","type":"text"}],"type":"topic","url":"\/documentation\/prismsdk\/scan","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Scan","kind":"symbol","role":"symbol","title":"Scan","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Scan"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSDKVersionString":{"abstract":[{"text":"Project version string for PrismSDK.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/prismsdk\/prismsdkversionstring","title":"PrismSDKVersionString","fragments":[{"text":"PrismSDKVersionString","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSDKVersionString"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/BodyShapePredictionPayload":{"abstract":[{"type":"text","text":"Body shape prediction post request payload"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BodyShapePredictionPayload"}],"title":"BodyShapePredictionPayload","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyShapePredictionPayload","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BodyShapePredictionPayload"}],"url":"\/documentation\/prismsdk\/bodyshapepredictionpayload"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/NewUser":{"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/NewUser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewUser"}],"navigatorTitle":[{"text":"NewUser","kind":"identifier"}],"title":"NewUser","url":"\/documentation\/prismsdk\/newuser","role":"symbol","abstract":[],"kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/SecondaryActionButtonStyle":{"type":"topic","navigatorTitle":[{"text":"SecondaryActionButtonStyle","kind":"identifier"}],"kind":"symbol","title":"SecondaryActionButtonStyle","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SecondaryActionButtonStyle","kind":"identifier"}],"url":"\/documentation\/prismsdk\/secondaryactionbuttonstyle","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/SecondaryActionButtonStyle","abstract":[{"text":"Used as the Primary Action button for all CTA style buttons","type":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraPermissionStatus":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraPermissionStatus","title":"CameraPermissionStatus","type":"topic","navigatorTitle":[{"text":"CameraPermissionStatus","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPermissionStatus"}],"url":"\/documentation\/prismsdk\/camerapermissionstatus","abstract":[{"type":"text","text":"The camera Permission Status"}],"kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismCaptureSession":{"title":"PrismCaptureSession","url":"\/documentation\/prismsdk\/prismcapturesession","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PrismCaptureSession","kind":"identifier"}],"navigatorTitle":[{"text":"PrismCaptureSession","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismCaptureSession","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Prism Capture Session"}],"role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/MotionDetector":{"abstract":[{"type":"text","text":"Helps monitor Device Rotation."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MotionDetector"}],"title":"MotionDetector","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/MotionDetector","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MotionDetector","kind":"identifier"}],"url":"\/documentation\/prismsdk\/motiondetector"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/AssetUrls":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/AssetUrls","title":"AssetUrls","type":"topic","abstract":[{"type":"text","text":"Asset URL’s contains the three files that can be downloaded for a scan"}],"navigatorTitle":[{"kind":"identifier","text":"AssetUrls"}],"url":"\/documentation\/prismsdk\/asseturls","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AssetUrls","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismThemeConfiguration":{"title":"PrismThemeConfiguration","abstract":[{"text":"Defines all of the available properties for theming the PrismSession","type":"text"}],"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismThemeConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/prismsdk\/prismthemeconfiguration","navigatorTitle":[{"text":"PrismThemeConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismThemeConfiguration"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/BodyShapePrediction":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BodyShapePrediction"}],"type":"topic","kind":"symbol","abstract":[{"text":"Body shape prediction response object","type":"text"}],"role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/BodyShapePrediction","navigatorTitle":[{"text":"BodyShapePrediction","kind":"identifier"}],"title":"BodyShapePrediction","url":"\/documentation\/prismsdk\/bodyshapeprediction"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/ApiClient":{"url":"\/documentation\/prismsdk\/apiclient","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ApiClient","kind":"identifier"}],"type":"topic","abstract":[{"text":"The base API Client utilized by domain clients, e.g. ScanClient, UserClient, etc.","type":"text"}],"title":"ApiClient","navigatorTitle":[{"kind":"identifier","text":"ApiClient"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ApiClient"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CaptureSessionConfiguration":{"title":"CaptureSessionConfiguration","url":"\/documentation\/prismsdk\/capturesessionconfiguration","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CaptureSessionConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CaptureSessionConfiguration","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSessionConfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Configurable properties for the Capture Session","type":"text"}],"role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PositioningProblem":{"type":"topic","abstract":[{"text":"Positioning Problems","type":"text"}],"navigatorTitle":[{"text":"PositioningProblem","kind":"identifier"}],"url":"\/documentation\/prismsdk\/positioningproblem","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PositioningProblem"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PositioningProblem","kind":"symbol","title":"PositioningProblem"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PositioningResult":{"title":"PositioningResult","navigatorTitle":[{"kind":"identifier","text":"PositioningResult"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PositioningResult","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PositioningResult"}],"url":"\/documentation\/prismsdk\/positioningresult","abstract":[{"text":"PositioningResult returns the high level results","type":"text"}],"kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/ApiClientBearerToken":{"title":"ApiClientBearerToken","navigatorTitle":[{"text":"ApiClientBearerToken","kind":"identifier"}],"abstract":[{"type":"text","text":"Type representing the Bearer Token for the API Client"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ApiClientBearerToken","url":"\/documentation\/prismsdk\/apiclientbearertoken","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ApiClientBearerToken"}],"type":"topic","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Sex":{"type":"topic","url":"\/documentation\/prismsdk\/sex","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sex","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Sex","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Sex"}],"title":"Sex","abstract":[{"type":"text","text":"The sex for the user"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSDKVersionNumber":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsdkversionnumber","fragments":[{"text":"PrismSDKVersionNumber","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSDKVersionNumber","title":"PrismSDKVersionNumber","abstract":[{"text":"Project version number for PrismSDK.","type":"text"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/ExistingUser":{"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/ExistingUser","type":"topic","url":"\/documentation\/prismsdk\/existinguser","title":"ExistingUser","navigatorTitle":[{"kind":"identifier","text":"ExistingUser"}],"abstract":[{"text":"Used for modifying an existing user in the Prism API","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ExistingUser","kind":"identifier"}],"role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionView":{"kind":"symbol","title":"PrismSessionView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionView"}],"abstract":[{"text":"The entire Capture Session Flow","type":"text"}],"url":"\/documentation\/prismsdk\/prismsessionview","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrismSessionView"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionView","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Paginated":{"title":"Paginated","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Paginated","abstract":[{"type":"text","text":"The Paginated response containing the results and pate info"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Paginated","kind":"identifier"}],"type":"topic","url":"\/documentation\/prismsdk\/paginated","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Paginated"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/NewScan":{"kind":"symbol","navigatorTitle":[{"text":"NewScan","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/NewScan","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewScan","kind":"identifier"}],"url":"\/documentation\/prismsdk\/newscan","abstract":[{"text":"Create a new scan","type":"text"}],"title":"NewScan"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CaptureError":{"abstract":[{"type":"text","text":"Capture Errors"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CaptureError"}],"title":"CaptureError","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureError","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureError","kind":"identifier"}],"url":"\/documentation\/prismsdk\/captureerror"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/SwiftUICore":{"url":"\/documentation\/prismsdk\/swiftuicore","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/SwiftUICore","abstract":[],"kind":"symbol","title":"SwiftUICore","type":"topic","role":"collection"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/Asset":{"navigatorTitle":[{"kind":"identifier","text":"Asset"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Asset"}],"url":"\/documentation\/prismsdk\/asset","title":"Asset","role":"symbol","abstract":[{"type":"text","text":"Asset model"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/Asset"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/UserClient":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"UserClient","kind":"identifier"}],"abstract":[{"text":"The UserClient contains all of the API calls for","type":"text"},{"type":"text","text":" "},{"text":"managing users.","type":"text"}],"title":"UserClient","type":"topic","kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/UserClient","url":"\/documentation\/prismsdk\/userclient","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserClient"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraBuffer":{"title":"CameraBuffer","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CameraBuffer","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns the full Camera Bummer"}],"type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraBuffer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraBuffer"}],"url":"\/documentation\/prismsdk\/camerabuffer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Capture UI","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController"],"anchor":"Capture-UI"},{"generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader"],"title":"Classes","anchor":"Classes"},{"generated":true,"anchor":"Variables","title":"Variables","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSDKVersionNumber","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSDKVersionString"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"PrismSessionViewController","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title"},{"op":"replace","value":[{"text":"PrismSessionViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle","value":[{"text":"PrismSessionViewController","kind":"identifier"}],"op":"replace"},{"value":"CameraSession","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title"},{"op":"replace","value":[{"text":"CameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments"},{"value":[{"kind":"identifier","text":"CameraSession"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title","value":"FileUploader","op":"replace"},{"value":[{"kind":"identifier","text":"FileUploader"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","value":[{"kind":"identifier","text":"FileUploader"}],"op":"replace"}]}]}