{"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/dataOutputSynchronizer(_:didOutput:)"]}],"variants":[{"paths":["\/documentation\/prismsdk\/camerasession\/avcapturedataoutputsynchronizerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/prismsdk\/camerasession\/avcapturedataoutputsynchronizerdelegate-implementations"]}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession"]]},"sections":[],"kind":"article","identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/AVCaptureDataOutputSynchronizerDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PrismSDK"}],"title":"AVCaptureDataOutputSynchronizerDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/dataOutputSynchronizer(_:didOutput:)":{"url":"\/documentation\/prismsdk\/camerasession\/dataoutputsynchronizer(_:didoutput:)","role":"symbol","navigatorTitle":[{"text":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/dataOutputSynchronizer(_:didOutput:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataOutputSynchronizer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureDataOutputSynchronizer","preciseIdentifier":"c:objc(cs)AVCaptureDataOutputSynchronizer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"text":"AVCaptureSynchronizedDataCollection","preciseIdentifier":"c:objc(cs)AVCaptureSynchronizedDataCollection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[],"title":"dataOutputSynchronizer(_:didOutput:)"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/dataOutputSynchronizer(_:didOutput:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title","value":"CameraSession"},{"value":[{"text":"CameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","value":[{"text":"CameraSession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession~1dataOutputSynchronizer(_:didOutput:)\/title","value":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession~1dataOutputSynchronizer(_:didOutput:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}