{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPosition"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","text":"Position","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The Camera to use. We only support front facing right now, but the"},{"type":"text","text":" "},{"text":"rear camera can also be used.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/camerasession\/cameraposition"]}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/cameraPosition","interfaceLanguage":"swift"},"metadata":{"externalID":"s:8PrismSDK13CameraSessionC14cameraPositionSo015AVCaptureDeviceF0Vvp","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"cameraPosition","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}],"modules":[{"name":"PrismSDK"}]},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/cameraPosition":{"url":"\/documentation\/prismsdk\/camerasession\/cameraposition","title":"cameraPosition","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/cameraPosition","abstract":[{"type":"text","text":"The Camera to use. We only support front facing right now, but the"},{"type":"text","text":" "},{"type":"text","text":"rear camera can also be used."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPosition","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title","value":"CameraSession"},{"op":"replace","value":[{"kind":"identifier","text":"CameraSession"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","op":"replace","value":[{"text":"CameraSession","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}