{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataOutputSynchronizer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"synchronizer","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureDataOutputSynchronizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDataOutputSynchronizer"},{"kind":"text","text":", "},{"text":"didOutput","kind":"externalParam"},{"kind":"text","text":" "},{"text":"synchronizedDataCollection","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureSynchronizedDataCollection","preciseIdentifier":"c:objc(cs)AVCaptureSynchronizedDataCollection"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:"}],"roleHeading":"Instance Method","title":"dataOutputSynchronizer(_:didOutput:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataOutputSynchronizer"},{"kind":"text","text":"("},{"text":"AVCaptureDataOutputSynchronizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDataOutputSynchronizer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureSynchronizedDataCollection","kind":"typeIdentifier","text":"AVCaptureSynchronizedDataCollection"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@CM@PrismSDK@objc(cs)CameraSession(im)dataOutputSynchronizer:didOutputSynchronizedDataCollection:","modules":[{"name":"PrismSDK"}],"extendedModule":"PrismSDK"},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/AVCaptureDataOutputSynchronizerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVCaptureDataOutputSynchronizerDelegate.dataOutputSynchronizer(_:didOutput:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/dataOutputSynchronizer(_:didOutput:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/camerasession\/dataoutputsynchronizer(_:didoutput:)"]},{"paths":["\/documentation\/prismsdk\/camerasession\/dataoutputsynchronizer(_:didoutput:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/AVCaptureDataOutputSynchronizerDelegate-Implementations":{"title":"AVCaptureDataOutputSynchronizerDelegate Implementations","kind":"article","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/AVCaptureDataOutputSynchronizerDelegate-Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/prismsdk\/camerasession\/avcapturedataoutputsynchronizerdelegate-implementations"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/dataOutputSynchronizer(_:didOutput:)":{"url":"\/documentation\/prismsdk\/camerasession\/dataoutputsynchronizer(_:didoutput:)","role":"symbol","navigatorTitle":[{"text":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/dataOutputSynchronizer(_:didOutput:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dataOutputSynchronizer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureDataOutputSynchronizer","preciseIdentifier":"c:objc(cs)AVCaptureDataOutputSynchronizer"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"text":"AVCaptureSynchronizedDataCollection","preciseIdentifier":"c:objc(cs)AVCaptureSynchronizedDataCollection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[],"title":"dataOutputSynchronizer(_:didOutput:)"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"dataOutputSynchronizer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVCaptureDataOutputSynchronizer","preciseIdentifier":"c:objc(cs)AVCaptureDataOutputSynchronizer"},{"kind":"text","text":" *) "},{"text":"synchronizer","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didOutputSynchronizedDataCollection:"},{"kind":"text","text":"("},{"text":"AVCaptureSynchronizedDataCollection","preciseIdentifier":"c:objc(cs)AVCaptureSynchronizedDataCollection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"synchronizedDataCollection","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession~1dataOutputSynchronizer(_:didOutput:)\/title","op":"replace","value":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"dataOutputSynchronizer:didOutputSynchronizedDataCollection:","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession~1dataOutputSynchronizer(_:didOutput:)\/fragments"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title","op":"replace","value":"CameraSession"},{"op":"replace","value":[{"kind":"identifier","text":"CameraSession"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments"},{"value":[{"kind":"identifier","text":"CameraSession"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle"}]}]}