{"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/orientation","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"orientation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/prismsdk\/camerasession\/orientation"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The Device orientation (landscape or portrait)","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"PrismSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"text":"AVCaptureVideoOrientation","preciseIdentifier":"c:@E@AVCaptureVideoOrientation","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"orientation","externalID":"s:8PrismSDK13CameraSessionC11orientationSo25AVCaptureVideoOrientationVvp"},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession"]]},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/orientation":{"type":"topic","abstract":[{"text":"The Device orientation (landscape or portrait)","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/orientation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@AVCaptureVideoOrientation","text":"AVCaptureVideoOrientation","kind":"typeIdentifier"}],"url":"\/documentation\/prismsdk\/camerasession\/orientation","title":"orientation","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CameraSession","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments","value":[{"text":"CameraSession","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CameraSession"}]}]}]}