{"sections":[],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/positionFeedback","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"positionFeedback","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8PrismSDK17DetectionFeedbackO","text":"DetectionFeedback","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"PrismSDK"}],"symbolKind":"property","roleHeading":"Instance Property","title":"positionFeedback","externalID":"s:8PrismSDK13CameraSessionC16positionFeedbackAA09DetectionF0OSgvp","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession"]]},"abstract":[{"type":"text","text":"An indicator of position acceptability"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/camerasession\/positionfeedback"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"Published","kind":"attribute","preciseIdentifier":"s:7Combine9PublishedV"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionFeedback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/DetectionFeedback","text":"DetectionFeedback","preciseIdentifier":"s:8PrismSDK17DetectionFeedbackO"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/DetectionFeedback":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DetectionFeedback","kind":"identifier"}],"url":"\/documentation\/prismsdk\/detectionfeedback","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/DetectionFeedback","title":"DetectionFeedback","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DetectionFeedback","kind":"identifier"}],"abstract":[{"type":"text","text":"DetectionFeedback returns the high level results"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/positionFeedback":{"type":"topic","abstract":[{"type":"text","text":"An indicator of position acceptability"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/positionFeedback","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"positionFeedback"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionFeedback","preciseIdentifier":"s:8PrismSDK17DetectionFeedbackO"},{"text":"?","kind":"text"}],"url":"\/documentation\/prismsdk\/camerasession\/positionfeedback","title":"positionFeedback","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"CameraSession","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title"},{"value":[{"text":"CameraSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","value":[{"text":"CameraSession","kind":"identifier"}],"op":"replace"}]}]}