{"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The permission status for the camera"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/camerasession\/status"]}],"metadata":{"modules":[{"name":"PrismSDK"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK22CameraPermissionStatusO","text":"CameraPermissionStatus"}],"externalID":"s:8PrismSDK13CameraSessionC6statusAA0C16PermissionStatusOvp","roleHeading":"Instance Property","title":"status"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"Published","kind":"attribute","preciseIdentifier":"s:7Combine9PublishedV"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraPermissionStatus","text":"CameraPermissionStatus","preciseIdentifier":"s:8PrismSDK22CameraPermissionStatusO"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/status"},"sections":[],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/status":{"type":"topic","abstract":[{"text":"The permission status for the camera","type":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/status","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraPermissionStatus","preciseIdentifier":"s:8PrismSDK22CameraPermissionStatusO","kind":"typeIdentifier"}],"url":"\/documentation\/prismsdk\/camerasession\/status","title":"status","role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraPermissionStatus":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraPermissionStatus","title":"CameraPermissionStatus","type":"topic","navigatorTitle":[{"text":"CameraPermissionStatus","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPermissionStatus"}],"url":"\/documentation\/prismsdk\/camerapermissionstatus","abstract":[{"type":"text","text":"The camera Permission Status"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title","value":"CameraSession"},{"value":[{"text":"CameraSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments"},{"value":[{"text":"CameraSession","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","op":"replace"}]}]}