{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visionDetection"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8PrismSDK20VisionDetectionStateO","kind":"typeIdentifier","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/VisionDetectionState","text":"VisionDetectionState"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection","interfaceLanguage":"swift"},"abstract":[{"text":"Enable or Disable Vision Detection.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"See "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection","type":"reference","isActive":true},{"text":" for more information","type":"text"}],"metadata":{"symbolKind":"property","role":"symbol","externalID":"s:8PrismSDK13CameraSessionC15visionDetectionAA06VisionF5StateOvp","title":"visionDetection","modules":[{"name":"PrismSDK"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visionDetection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8PrismSDK20VisionDetectionStateO","text":"VisionDetectionState","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/camerasession\/visiondetection"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession":{"title":"CameraSession","abstract":[{"type":"text","text":"The Camera Session used to record and determine"},{"type":"text","text":" "},{"type":"text","text":"poses from the user."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraSession","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession","navigatorTitle":[{"kind":"identifier","text":"CameraSession"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CameraSession/visionDetection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"visionDetection","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VisionDetectionState","preciseIdentifier":"s:8PrismSDK20VisionDetectionStateO"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection","type":"topic","title":"visionDetection","abstract":[{"type":"text","text":"Enable or Disable Vision Detection."},{"type":"text","text":" "},{"type":"text","text":"See "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CameraSession\/visionDetection","isActive":true,"type":"reference"},{"type":"text","text":" for more information"}],"role":"symbol","url":"\/documentation\/prismsdk\/camerasession\/visiondetection"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/VisionDetectionState":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"VisionDetectionState"}],"navigatorTitle":[{"text":"VisionDetectionState","kind":"identifier"}],"title":"VisionDetectionState","abstract":[{"type":"text","text":"Vision Detection State"}],"url":"\/documentation\/prismsdk\/visiondetectionstate","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/VisionDetectionState","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/title","value":"CameraSession"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"CameraSession"}]},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1CameraSession\/navigatorTitle","value":[{"kind":"identifier","text":"CameraSession"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}