{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"willDismiss"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","text":"PrismSessionViewController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"controller","content":[{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"},{"text":" that you wish to dismiss","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"This ","type":"text"},{"code":"willDimiss","type":"codeVoice"},{"text":" method allows you to perform any actions you need before calling the","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"controller.dismiss(animated: true)"},{"text":" method. This is required to dismiss the presented view controller.","type":"text"}],"type":"paragraph"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"PrismSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"willDismiss"},{"kind":"text","text":": "},{"text":"PrismSessionViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController"},{"text":")","kind":"text"}],"required":true,"title":"prismSession(willDismiss:)","externalID":"s:8PrismSDK0A29SessionViewControllerDelegateP05prismC011willDismissyAA0acdE0C_tF"},"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(willDismiss:)","interfaceLanguage":"swift"},"abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","type":"reference","isActive":true},{"type":"text","text":" that will dimiss"}],"variants":[{"paths":["\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(willdismiss:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate/prismSession(willDismiss:)":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(willdismiss:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"kind":"text","text":"("},{"text":"willDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PrismSessionViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController"},{"kind":"text","text":")"}],"title":"prismSession(willDismiss:)","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(willDismiss:)","abstract":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true},{"type":"text","text":" that will dimiss"}],"required":true,"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title","value":"PrismSessionViewController","op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments","value":[{"kind":"identifier","text":"PrismSessionViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle","value":[{"kind":"identifier","text":"PrismSessionViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}