{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(_:didchangestatus:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(_:didChangeStatus:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"text":"PrismSessionViewController","kind":"typeIdentifier","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController"},{"text":", ","kind":"text"},{"text":"didChangeStatus","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK19CaptureSessionStateO","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSessionState","text":"CaptureSessionState"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"controller","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"reference","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true},{"text":" returning the archive","type":"text"}]}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"The status of the CaptureSession","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This is called everytime a state changes within the capture flow."},{"text":" ","type":"text"},{"type":"text","text":"This can be used for analytic events."}],"type":"paragraph"}]}],"abstract":[{"text":"When the capture state changes","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"s:8PrismSDK0A29SessionViewControllerDelegateP05prismC0_15didChangeStatusyAA0acdE0C_AA07CaptureC5StateOtF","roleHeading":"Instance Method","modules":[{"name":"PrismSDK"}],"required":true,"symbolKind":"method","role":"symbol","title":"prismSession(_:didChangeStatus:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PrismSessionViewController","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeStatus"},{"kind":"text","text":": "},{"text":"CaptureSessionState","kind":"typeIdentifier","preciseIdentifier":"s:8PrismSDK19CaptureSessionStateO"},{"text":")","kind":"text"}]},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CaptureSession":{"url":"\/documentation\/prismsdk\/capturesession","abstract":[{"type":"text","text":"Capture Session"}],"navigatorTitle":[{"text":"CaptureSession","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureSession"}],"title":"CaptureSession","kind":"symbol","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSession","role":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"title":"PrismSessionViewControllerDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewControllerDelegate"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate","abstract":[{"type":"text","text":"The delegate callbacks for the "},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","isActive":true,"type":"reference"}],"type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewController":{"kind":"symbol","title":"PrismSessionViewController","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PrismSessionViewController"}],"url":"\/documentation\/prismsdk\/prismsessionviewcontroller","type":"topic","abstract":[{"text":"PrismSessionViewController functions as the one-stop Capture View.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The PrismSessionViewController handles all of the capturing, recording,"},{"type":"text","text":" "},{"type":"text","text":"and posing of the person. This is to help simplify the entire process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PrismSessionViewController"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/PrismSessionViewControllerDelegate/prismSession(_:didChangeStatus:)":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/PrismSessionViewControllerDelegate\/prismSession(_:didChangeStatus:)","kind":"symbol","title":"prismSession(_:didChangeStatus:)","url":"\/documentation\/prismsdk\/prismsessionviewcontrollerdelegate\/prismsession(_:didchangestatus:)","abstract":[{"text":"When the capture state changes","type":"text"}],"role":"symbol","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prismSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"PrismSessionViewController","preciseIdentifier":"c:@M@PrismSDK@objc(cs)PrismSessionViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didChangeStatus"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8PrismSDK19CaptureSessionStateO","kind":"typeIdentifier","text":"CaptureSessionState"},{"kind":"text","text":")"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/CaptureSessionState":{"abstract":[{"text":"The states of the ","type":"text"},{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSession","isActive":true,"type":"reference"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureSessionState"}],"kind":"symbol","type":"topic","url":"\/documentation\/prismsdk\/capturesessionstate","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/CaptureSessionState","title":"CaptureSessionState","navigatorTitle":[{"text":"CaptureSessionState","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PrismSessionViewController","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/title"},{"value":[{"text":"PrismSessionViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/fragments","op":"replace"},{"value":[{"text":"PrismSessionViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1PrismSessionViewController\/navigatorTitle"}]}]}