{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"extendedModule":"Combine","title":"objectWillChange","symbolKind":"property","platforms":[{"introducedAt":"13.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iPadOS","unavailable":false},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"13.0"},{"name":"macOS","introducedAt":"10.15","unavailable":false,"deprecated":false,"beta":false},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"tvOS"},{"introducedAt":"6.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"ObjectWillChangePublisher"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"ObservableObjectPublisher"},{"text":".","type":"text"}]},"externalID":"s:7Combine16ObservableObjectPA2A0bC9PublisherC0c10WillChangeD0RtzrlE06objecteF0AEvp::SYNTHESIZED::c:@M@PrismSDK@objc(cs)FileUploader","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"objectWillChange","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ObservableObjectPublisher","kind":"typeIdentifier","preciseIdentifier":"s:7Combine25ObservableObjectPublisherC"}],"role":"symbol","modules":[{"name":"PrismSDK","relatedModules":["Combine"]}],"roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/objectwillchange"]}],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/objectWillChange","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/ObservableObject-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"ObservableObject.objectWillChange"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"objectWillChange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7Combine25ObservableObjectPublisherC","text":"ObservableObjectPublisher","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/objectWillChange":{"kind":"symbol","type":"topic","title":"objectWillChange","url":"\/documentation\/prismsdk\/fileuploader\/objectwillchange","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"objectWillChange","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Combine25ObservableObjectPublisherC","kind":"typeIdentifier","text":"ObservableObjectPublisher"}],"abstract":[],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/objectWillChange","conformance":{"constraints":[{"type":"codeVoice","code":"ObjectWillChangePublisher"},{"type":"text","text":" is "},{"type":"codeVoice","code":"ObservableObjectPublisher"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/ObservableObject-Implementations":{"url":"\/documentation\/prismsdk\/fileuploader\/observableobject-implementations","kind":"article","title":"ObservableObject Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/ObservableObject-Implementations","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title","value":"FileUploader","op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments","value":[{"text":"FileUploader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","op":"replace","value":[{"text":"FileUploader","kind":"identifier"}]}]}]}