{"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/observableobject-implementations"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader"]]},"topicSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/objectWillChange"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/ObservableObject-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"PrismSDK"}],"roleHeading":"API Collection","title":"ObservableObject Implementations","role":"collectionGroup"},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/objectWillChange":{"kind":"symbol","type":"topic","title":"objectWillChange","url":"\/documentation\/prismsdk\/fileuploader\/objectwillchange","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"objectWillChange","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7Combine25ObservableObjectPublisherC","kind":"typeIdentifier","text":"ObservableObjectPublisher"}],"abstract":[],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/objectWillChange","conformance":{"constraints":[{"type":"codeVoice","code":"ObjectWillChangePublisher"},{"type":"text","text":" is "},{"type":"codeVoice","code":"ObservableObjectPublisher"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title","value":"FileUploader"},{"value":[{"kind":"identifier","text":"FileUploader"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","value":[{"kind":"identifier","text":"FileUploader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}