{"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/uploadedFile","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"Published","preciseIdentifier":"s:7Combine9PublishedV"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uploadedFile"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"PrismSDK"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uploadedFile","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"uploadedFile","externalID":"s:8PrismSDK12FileUploaderC08uploadedC0Sbvp"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/uploadedfile"]}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader"]]},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/uploadedFile":{"abstract":[],"url":"\/documentation\/prismsdk\/fileuploader\/uploadedfile","role":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/uploadedFile","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"uploadedFile","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"uploadedFile"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title","value":"FileUploader"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments","op":"replace","value":[{"kind":"identifier","text":"FileUploader"}]},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","value":[{"text":"FileUploader","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}