{"metadata":{"title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","roleHeading":"Instance Method","modules":[{"name":"PrismSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSendBodyData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V","text":"Int64"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalBytesSent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":", "},{"text":"totalBytesExpectedToSend","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@CM@PrismSDK@objc(cs)FileUploader(im)URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","navigatorTitle":[{"kind":"identifier","text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:"}],"extendedModule":"PrismSDK","symbolKind":"method","role":"symbol"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"URLSessionTaskDelegate.urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":", "},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"text":", ","kind":"text"},{"text":"didSendBodyData","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"bytesSent","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"text":", ","kind":"text"},{"text":"totalBytesSent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"totalBytesExpectedToSend","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)"]}],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"]]},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/URLSessionTaskDelegate-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiontaskdelegate-implementations","type":"topic","role":"collectionGroup","title":"URLSessionTaskDelegate Implementations","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)":{"url":"\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)","navigatorTitle":[{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"text":": ","kind":"text"},{"text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSendBodyData"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"totalBytesSent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"text":"totalBytesExpectedToSend","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","type":"topic","abstract":[],"role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"URLSession:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"session"},{"text":" ","kind":"text"},{"kind":"identifier","text":"task:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"NSURLSessionTask"},{"text":" *) ","kind":"text"},{"text":"task","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSendBodyData:"},{"kind":"text","text":"("},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bytesSent"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalBytesSent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t","text":"int64_t"},{"text":") ","kind":"text"},{"text":"totalBytesSent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"totalBytesExpectedToSend:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"totalBytesExpectedToSend"},{"text":";","kind":"text"}]}]}},{"value":"FileUploader","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title"},{"op":"replace","value":[{"text":"FileUploader","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments"},{"value":[{"text":"FileUploader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/title","value":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:"}]}]}]}