{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader"]]},"topicSections":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didCompleteWithError:)","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"article","variants":[{"paths":["\/documentation\/prismsdk\/fileuploader\/urlsessiontaskdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/prismsdk\/fileuploader\/urlsessiontaskdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"PrismSDK"}],"title":"URLSessionTaskDelegate Implementations"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)":{"url":"\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didsendbodydata:totalbytessent:totalbytesexpectedtosend:)","navigatorTitle":[{"text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","kind":"identifier"}],"title":"urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"text":": ","kind":"text"},{"text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSendBodyData"},{"text":": ","kind":"text"},{"text":"Int64","preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"totalBytesSent","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","kind":"typeIdentifier","text":"Int64"},{"kind":"text","text":", "},{"text":"totalBytesExpectedToSend","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)","type":"topic","abstract":[],"role":"symbol","kind":"symbol"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSession(_:task:didCompleteWithError:)":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didCompleteWithError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"task"},{"text":": ","kind":"text"},{"text":"URLSessionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"text":"didCompleteWithError","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"URLSession:task:didCompleteWithError:","kind":"identifier"}],"type":"topic","url":"\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didcompletewitherror:)","kind":"symbol","abstract":[],"title":"urlSession(_:task:didCompleteWithError:)"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didCompleteWithError:)","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/title","value":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:)\/fragments"},{"value":"URLSession:task:didCompleteWithError:","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didCompleteWithError:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"URLSession:task:didCompleteWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didCompleteWithError:)\/fragments"},{"value":"FileUploader","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title"},{"value":[{"text":"FileUploader","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","value":[{"kind":"identifier","text":"FileUploader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}