{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader"]]},"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:didBecomeInvalidWithError:)","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSessionDidFinishEvents(forBackgroundURLSession:)"]}],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/urlsessiondelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/prismsdk\/fileuploader\/urlsessiondelegate-implementations"]}],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"PrismSDK"}],"title":"URLSessionDelegate Implementations"},"sections":[],"identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionDelegate-Implementations","interfaceLanguage":"swift"},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSession(_:didBecomeInvalidWithError:)":{"role":"symbol","title":"urlSession(_:didBecomeInvalidWithError:)","navigatorTitle":[{"kind":"identifier","text":"URLSession:didBecomeInvalidWithError:"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:didBecomeInvalidWithError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"text":"(","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didBecomeInvalidWithError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"url":"\/documentation\/prismsdk\/fileuploader\/urlsession(_:didbecomeinvalidwitherror:)"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSessionDidFinishEvents(forBackgroundURLSession:)":{"title":"urlSessionDidFinishEvents(forBackgroundURLSession:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionDidFinishEvents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBackgroundURLSession","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"URLSessionDidFinishEventsForBackgroundURLSession:","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSessionDidFinishEvents(forBackgroundURLSession:)","role":"symbol","kind":"symbol","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiondidfinishevents(forbackgroundurlsession:)","type":"topic","abstract":[]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:didBecomeInvalidWithError:)","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSessionDidFinishEvents(forBackgroundURLSession:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"URLSession:didBecomeInvalidWithError:","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:didBecomeInvalidWithError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"URLSession:didBecomeInvalidWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:didBecomeInvalidWithError:)\/fragments"},{"value":"URLSessionDidFinishEventsForBackgroundURLSession:","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"URLSessionDidFinishEventsForBackgroundURLSession:","kind":"identifier"}],"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/fragments"},{"value":"FileUploader","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title","op":"replace"},{"value":[{"kind":"identifier","text":"FileUploader"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments"},{"value":[{"text":"FileUploader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}