{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSessionDidFinishEvents(forBackgroundURLSession:)"},"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionDelegate-Implementations"]]},"metadata":{"role":"symbol","title":"urlSessionDidFinishEvents(forBackgroundURLSession:)","symbolKind":"method","externalID":"c:@CM@PrismSDK@objc(cs)FileUploader(im)URLSessionDidFinishEventsForBackgroundURLSession:","modules":[{"name":"PrismSDK"}],"navigatorTitle":[{"text":"URLSessionDidFinishEventsForBackgroundURLSession:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"urlSessionDidFinishEvents","kind":"identifier"},{"kind":"text","text":"("},{"text":"forBackgroundURLSession","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":")","kind":"text"}],"extendedModule":"PrismSDK"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"URLSessionDelegate.urlSessionDidFinishEvents(forBackgroundURLSession:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/urlsessiondidfinishevents(forbackgroundurlsession:)"]},{"paths":["\/documentation\/prismsdk\/fileuploader\/urlsessiondidfinishevents(forbackgroundurlsession:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSessionDidFinishEvents"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forBackgroundURLSession"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"text":": ","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/URLSessionDelegate-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiondelegate-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionDelegate-Implementations","title":"URLSessionDelegate Implementations"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSessionDidFinishEvents(forBackgroundURLSession:)":{"title":"urlSessionDidFinishEvents(forBackgroundURLSession:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSessionDidFinishEvents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forBackgroundURLSession","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"URLSessionDidFinishEventsForBackgroundURLSession:","kind":"identifier"}],"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSessionDidFinishEvents(forBackgroundURLSession:)","role":"symbol","kind":"symbol","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiondidfinishevents(forbackgroundurlsession:)","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"URLSessionDidFinishEventsForBackgroundURLSession:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"URLSessionDidFinishEventsForBackgroundURLSession:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"URLSessionDidFinishEventsForBackgroundURLSession:"},{"kind":"text","text":"("},{"text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"FileUploader","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments","value":[{"text":"FileUploader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","value":[{"text":"FileUploader","kind":"identifier"}],"op":"replace"},{"value":"URLSessionDidFinishEventsForBackgroundURLSession:","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSessionDidFinishEvents(forBackgroundURLSession:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSessionDidFinishEventsForBackgroundURLSession:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}