{"kind":"symbol","identifier":{"url":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didCompleteWithError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"session","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask"},{"text":", ","kind":"text"},{"text":"didCompleteWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"URLSessionTaskDelegate.urlSession(_:task:didCompleteWithError:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didcompletewitherror:)"]},{"paths":["\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didcompletewitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"PrismSDK"}],"roleHeading":"Instance Method","symbolKind":"method","extendedModule":"PrismSDK","navigatorTitle":[{"text":"URLSession:task:didCompleteWithError:","kind":"identifier"}],"externalID":"c:@CM@PrismSDK@objc(cs)FileUploader(im)URLSession:task:didCompleteWithError:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier","text":"URLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?)","kind":"text"}],"title":"urlSession(_:task:didCompleteWithError:)"},"references":{"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader","url":"\/documentation\/prismsdk\/fileuploader","kind":"symbol","type":"topic","role":"symbol","title":"FileUploader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FileUploader"}],"abstract":[{"text":"File Uploader handles uploading the Scan","type":"text"}],"navigatorTitle":[{"text":"FileUploader","kind":"identifier"}]},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK":{"abstract":[{"type":"text","text":"Full Body Scanning"}],"kind":"symbol","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK","title":"PrismSDK","url":"\/documentation\/prismsdk","role":"collection","type":"topic"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/URLSessionTaskDelegate-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/prismsdk\/fileuploader\/urlsessiontaskdelegate-implementations","type":"topic","role":"collectionGroup","title":"URLSessionTaskDelegate Implementations","identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/URLSessionTaskDelegate-Implementations"},"doc://tech.prismlabs.prismsdk/documentation/PrismSDK/FileUploader/urlSession(_:task:didCompleteWithError:)":{"identifier":"doc:\/\/tech.prismlabs.prismsdk\/documentation\/PrismSDK\/FileUploader\/urlSession(_:task:didCompleteWithError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urlSession"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"task"},{"text":": ","kind":"text"},{"text":"URLSessionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"text":"didCompleteWithError","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"URLSession:task:didCompleteWithError:","kind":"identifier"}],"type":"topic","url":"\/documentation\/prismsdk\/fileuploader\/urlsession(_:task:didcompletewitherror:)","kind":"symbol","abstract":[],"title":"urlSession(_:task:didCompleteWithError:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"URLSession:task:didCompleteWithError:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"URLSession:task:didCompleteWithError:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"URLSession:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"NSURLSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"task:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier","text":"NSURLSessionTask"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"task"},{"text":" ","kind":"text"},{"text":"didCompleteWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"FileUploader","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/title"},{"path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/fragments","value":[{"text":"FileUploader","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader\/navigatorTitle","value":[{"text":"FileUploader","kind":"identifier"}]},{"value":"URLSession:task:didCompleteWithError:","op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didCompleteWithError:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1tech.prismlabs.prismsdk~1documentation~1PrismSDK~1FileUploader~1urlSession(_:task:didCompleteWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSession:task:didCompleteWithError:","kind":"identifier"}]}]}]}